/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChromeTabs: typeof import('./src/components/tabs/chrome-tabs.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/dropdown.vue')['default']
    RenderTemp: typeof import('./src/components/tabs/render-temp.vue')['default']
    Terminal: typeof import('./src/components/terminal/terminal.vue')['default']
  }
}
