// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFoldOrHost(arg1) {
  return window['go']['logic']['Logic']['AddFoldOrHost'](arg1);
}

export function AddKey(arg1) {
  return window['go']['logic']['Logic']['AddKey'](arg1);
}

export function ClosePty(arg1) {
  return window['go']['logic']['Logic']['ClosePty'](arg1);
}

export function CloseSftpClient(arg1) {
  return window['go']['logic']['Logic']['CloseSftpClient'](arg1);
}

export function CreateLocalPty(arg1) {
  return window['go']['logic']['Logic']['CreateLocalPty'](arg1);
}

export function CreateSshPty(arg1, arg2, arg3, arg4) {
  return window['go']['logic']['Logic']['CreateSshPty'](arg1, arg2, arg3, arg4);
}

export function CreateSshPtyWithJumper(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['logic']['Logic']['CreateSshPtyWithJumper'](arg1, arg2, arg3, arg4, arg5);
}

export function DelFoldOrHost(arg1, arg2) {
  return window['go']['logic']['Logic']['DelFoldOrHost'](arg1, arg2);
}

export function DelKey(arg1) {
  return window['go']['logic']['Logic']['DelKey'](arg1);
}

export function ExportData() {
  return window['go']['logic']['Logic']['ExportData']();
}

export function GetFolds() {
  return window['go']['logic']['Logic']['GetFolds']();
}

export function GetFoldsAndHosts(arg1) {
  return window['go']['logic']['Logic']['GetFoldsAndHosts'](arg1);
}

export function GetHosts(arg1) {
  return window['go']['logic']['Logic']['GetHosts'](arg1);
}

export function GetKeyList(arg1) {
  return window['go']['logic']['Logic']['GetKeyList'](arg1);
}

export function GetLocalPtyList() {
  return window['go']['logic']['Logic']['GetLocalPtyList']();
}

export function GetStats(arg1) {
  return window['go']['logic']['Logic']['GetStats'](arg1);
}

export function ImportData() {
  return window['go']['logic']['Logic']['ImportData']();
}

export function IsRunAsAdmin() {
  return window['go']['logic']['Logic']['IsRunAsAdmin']();
}

export function OpenLink(arg1) {
  return window['go']['logic']['Logic']['OpenLink'](arg1);
}

export function OsGoos() {
  return window['go']['logic']['Logic']['OsGoos']();
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['logic']['Logic']['ResizePty'](arg1, arg2, arg3);
}

export function RunAsAdmin() {
  return window['go']['logic']['Logic']['RunAsAdmin']();
}

export function SftpDelete(arg1, arg2) {
  return window['go']['logic']['Logic']['SftpDelete'](arg1, arg2);
}

export function SftpDir(arg1, arg2) {
  return window['go']['logic']['Logic']['SftpDir'](arg1, arg2);
}

export function SftpDownload(arg1, arg2) {
  return window['go']['logic']['Logic']['SftpDownload'](arg1, arg2);
}

export function SftpHomeDir(arg1) {
  return window['go']['logic']['Logic']['SftpHomeDir'](arg1);
}

export function SftpUploadDirectory(arg1, arg2) {
  return window['go']['logic']['Logic']['SftpUploadDirectory'](arg1, arg2);
}

export function SftpUploadMultipleFiles(arg1, arg2) {
  return window['go']['logic']['Logic']['SftpUploadMultipleFiles'](arg1, arg2);
}

export function UpdFoldOrHost(arg1) {
  return window['go']['logic']['Logic']['UpdFoldOrHost'](arg1);
}

export function UpdKey(arg1) {
  return window['go']['logic']['Logic']['UpdKey'](arg1);
}

export function WriteToPty(arg1, arg2) {
  return window['go']['logic']['Logic']['WriteToPty'](arg1, arg2);
}
