// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFoldOrHost(arg1) {
  return window['go']['logic']['Logic']['AddFoldOrHost'](arg1);
}

export function AddKey(arg1) {
  return window['go']['logic']['Logic']['AddKey'](arg1);
}

export function ClosePty(arg1) {
  return window['go']['logic']['Logic']['ClosePty'](arg1);
}

export function CreateLocalPty(arg1) {
  return window['go']['logic']['Logic']['CreateLocalPty'](arg1);
}

export function CreateSshPty(arg1, arg2, arg3, arg4) {
  return window['go']['logic']['Logic']['CreateSshPty'](arg1, arg2, arg3, arg4);
}

export function DelFoldOrHost(arg1, arg2) {
  return window['go']['logic']['Logic']['DelFoldOrHost'](arg1, arg2);
}

export function DelKey(arg1) {
  return window['go']['logic']['Logic']['DelKey'](arg1);
}

export function Dir(arg1, arg2) {
  return window['go']['logic']['Logic']['Dir'](arg1, arg2);
}

export function Download(arg1, arg2) {
  return window['go']['logic']['Logic']['Download'](arg1, arg2);
}

export function GetFolds() {
  return window['go']['logic']['Logic']['GetFolds']();
}

export function GetFoldsAndHosts(arg1) {
  return window['go']['logic']['Logic']['GetFoldsAndHosts'](arg1);
}

export function GetHosts(arg1) {
  return window['go']['logic']['Logic']['GetHosts'](arg1);
}

export function GetKeyList(arg1) {
  return window['go']['logic']['Logic']['GetKeyList'](arg1);
}

export function GetLocalPtyList() {
  return window['go']['logic']['Logic']['GetLocalPtyList']();
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['logic']['Logic']['ResizePty'](arg1, arg2, arg3);
}

export function UpdFoldOrHost(arg1) {
  return window['go']['logic']['Logic']['UpdFoldOrHost'](arg1);
}

export function UpdKey(arg1) {
  return window['go']['logic']['Logic']['UpdKey'](arg1);
}

export function UploadDirectory(arg1, arg2) {
  return window['go']['logic']['Logic']['UploadDirectory'](arg1, arg2);
}

export function UploadMultipleFiles(arg1, arg2) {
  return window['go']['logic']['Logic']['UploadMultipleFiles'](arg1, arg2);
}

export function WriteToPty(arg1, arg2) {
  return window['go']['logic']['Logic']['WriteToPty'](arg1, arg2);
}
