// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"terminal/ent/folders"
	"terminal/ent/hosts"
	"terminal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FoldersQuery is the builder for querying Folders entities.
type FoldersQuery struct {
	config
	ctx          *QueryContext
	order        []folders.OrderOption
	inters       []Interceptor
	predicates   []predicate.Folders
	withParent   *FoldersQuery
	withChildren *FoldersQuery
	withHost     *HostsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FoldersQuery builder.
func (fq *FoldersQuery) Where(ps ...predicate.Folders) *FoldersQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FoldersQuery) Limit(limit int) *FoldersQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FoldersQuery) Offset(offset int) *FoldersQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FoldersQuery) Unique(unique bool) *FoldersQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FoldersQuery) Order(o ...folders.OrderOption) *FoldersQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryParent chains the current query on the "parent" edge.
func (fq *FoldersQuery) QueryParent() *FoldersQuery {
	query := (&FoldersClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(folders.Table, folders.FieldID, selector),
			sqlgraph.To(folders.Table, folders.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, folders.ParentTable, folders.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (fq *FoldersQuery) QueryChildren() *FoldersQuery {
	query := (&FoldersClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(folders.Table, folders.FieldID, selector),
			sqlgraph.To(folders.Table, folders.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, folders.ChildrenTable, folders.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHost chains the current query on the "host" edge.
func (fq *FoldersQuery) QueryHost() *HostsQuery {
	query := (&HostsClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(folders.Table, folders.FieldID, selector),
			sqlgraph.To(hosts.Table, hosts.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, folders.HostTable, folders.HostColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Folders entity from the query.
// Returns a *NotFoundError when no Folders was found.
func (fq *FoldersQuery) First(ctx context.Context) (*Folders, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{folders.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FoldersQuery) FirstX(ctx context.Context) *Folders {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Folders ID from the query.
// Returns a *NotFoundError when no Folders ID was found.
func (fq *FoldersQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{folders.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FoldersQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Folders entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Folders entity is found.
// Returns a *NotFoundError when no Folders entities are found.
func (fq *FoldersQuery) Only(ctx context.Context) (*Folders, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{folders.Label}
	default:
		return nil, &NotSingularError{folders.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FoldersQuery) OnlyX(ctx context.Context) *Folders {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Folders ID in the query.
// Returns a *NotSingularError when more than one Folders ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FoldersQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{folders.Label}
	default:
		err = &NotSingularError{folders.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FoldersQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FoldersSlice.
func (fq *FoldersQuery) All(ctx context.Context) ([]*Folders, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Folders, *FoldersQuery]()
	return withInterceptors[[]*Folders](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FoldersQuery) AllX(ctx context.Context) []*Folders {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Folders IDs.
func (fq *FoldersQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err = fq.Select(folders.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FoldersQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FoldersQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FoldersQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FoldersQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FoldersQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FoldersQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FoldersQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FoldersQuery) Clone() *FoldersQuery {
	if fq == nil {
		return nil
	}
	return &FoldersQuery{
		config:       fq.config,
		ctx:          fq.ctx.Clone(),
		order:        append([]folders.OrderOption{}, fq.order...),
		inters:       append([]Interceptor{}, fq.inters...),
		predicates:   append([]predicate.Folders{}, fq.predicates...),
		withParent:   fq.withParent.Clone(),
		withChildren: fq.withChildren.Clone(),
		withHost:     fq.withHost.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FoldersQuery) WithParent(opts ...func(*FoldersQuery)) *FoldersQuery {
	query := (&FoldersClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withParent = query
	return fq
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FoldersQuery) WithChildren(opts ...func(*FoldersQuery)) *FoldersQuery {
	query := (&FoldersClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withChildren = query
	return fq
}

// WithHost tells the query-builder to eager-load the nodes that are connected to
// the "host" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FoldersQuery) WithHost(opts ...func(*HostsQuery)) *FoldersQuery {
	query := (&HostsClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withHost = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Folders.Query().
//		GroupBy(folders.FieldLabel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FoldersQuery) GroupBy(field string, fields ...string) *FoldersGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FoldersGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = folders.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//	}
//
//	client.Folders.Query().
//		Select(folders.FieldLabel).
//		Scan(ctx, &v)
func (fq *FoldersQuery) Select(fields ...string) *FoldersSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FoldersSelect{FoldersQuery: fq}
	sbuild.label = folders.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FoldersSelect configured with the given aggregations.
func (fq *FoldersQuery) Aggregate(fns ...AggregateFunc) *FoldersSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FoldersQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !folders.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FoldersQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Folders, error) {
	var (
		nodes       = []*Folders{}
		_spec       = fq.querySpec()
		loadedTypes = [3]bool{
			fq.withParent != nil,
			fq.withChildren != nil,
			fq.withHost != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Folders).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Folders{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withParent; query != nil {
		if err := fq.loadParent(ctx, query, nodes, nil,
			func(n *Folders, e *Folders) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withChildren; query != nil {
		if err := fq.loadChildren(ctx, query, nodes,
			func(n *Folders) { n.Edges.Children = []*Folders{} },
			func(n *Folders, e *Folders) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := fq.withHost; query != nil {
		if err := fq.loadHost(ctx, query, nodes, nil,
			func(n *Folders, e *Hosts) { n.Edges.Host = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FoldersQuery) loadParent(ctx context.Context, query *FoldersQuery, nodes []*Folders, init func(*Folders), assign func(*Folders, *Folders)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Folders)
	for i := range nodes {
		fk := nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(folders.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FoldersQuery) loadChildren(ctx context.Context, query *FoldersQuery, nodes []*Folders, init func(*Folders), assign func(*Folders, *Folders)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Folders)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(folders.FieldParentID)
	}
	query.Where(predicate.Folders(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(folders.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (fq *FoldersQuery) loadHost(ctx context.Context, query *HostsQuery, nodes []*Folders, init func(*Folders), assign func(*Folders, *Hosts)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Folders)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hosts.FieldFolderID)
	}
	query.Where(predicate.Hosts(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(folders.HostColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FolderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "folder_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *FoldersQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FoldersQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(folders.Table, folders.Columns, sqlgraph.NewFieldSpec(folders.FieldID, field.TypeInt))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, folders.FieldID)
		for i := range fields {
			if fields[i] != folders.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if fq.withParent != nil {
			_spec.Node.AddColumnOnce(folders.FieldParentID)
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FoldersQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(folders.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = folders.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FoldersGroupBy is the group-by builder for Folders entities.
type FoldersGroupBy struct {
	selector
	build *FoldersQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FoldersGroupBy) Aggregate(fns ...AggregateFunc) *FoldersGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FoldersGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FoldersQuery, *FoldersGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FoldersGroupBy) sqlScan(ctx context.Context, root *FoldersQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FoldersSelect is the builder for selecting fields of Folders entities.
type FoldersSelect struct {
	*FoldersQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FoldersSelect) Aggregate(fns ...AggregateFunc) *FoldersSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FoldersSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FoldersQuery, *FoldersSelect](ctx, fs.FoldersQuery, fs, fs.inters, v)
}

func (fs *FoldersSelect) sqlScan(ctx context.Context, root *FoldersQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
