// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"terminal/ent/folders"
	"terminal/ent/hosts"
	"terminal/ent/keys"
	"terminal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HostsQuery is the builder for querying Hosts entities.
type HostsQuery struct {
	config
	ctx        *QueryContext
	order      []hosts.OrderOption
	inters     []Interceptor
	predicates []predicate.Hosts
	withFolder *FoldersQuery
	withKey    *KeysQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HostsQuery builder.
func (hq *HostsQuery) Where(ps ...predicate.Hosts) *HostsQuery {
	hq.predicates = append(hq.predicates, ps...)
	return hq
}

// Limit the number of records to be returned by this query.
func (hq *HostsQuery) Limit(limit int) *HostsQuery {
	hq.ctx.Limit = &limit
	return hq
}

// Offset to start from.
func (hq *HostsQuery) Offset(offset int) *HostsQuery {
	hq.ctx.Offset = &offset
	return hq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hq *HostsQuery) Unique(unique bool) *HostsQuery {
	hq.ctx.Unique = &unique
	return hq
}

// Order specifies how the records should be ordered.
func (hq *HostsQuery) Order(o ...hosts.OrderOption) *HostsQuery {
	hq.order = append(hq.order, o...)
	return hq
}

// QueryFolder chains the current query on the "folder" edge.
func (hq *HostsQuery) QueryFolder() *FoldersQuery {
	query := (&FoldersClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hosts.Table, hosts.FieldID, selector),
			sqlgraph.To(folders.Table, folders.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, hosts.FolderTable, hosts.FolderColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryKey chains the current query on the "key" edge.
func (hq *HostsQuery) QueryKey() *KeysQuery {
	query := (&KeysClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hosts.Table, hosts.FieldID, selector),
			sqlgraph.To(keys.Table, keys.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hosts.KeyTable, hosts.KeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Hosts entity from the query.
// Returns a *NotFoundError when no Hosts was found.
func (hq *HostsQuery) First(ctx context.Context) (*Hosts, error) {
	nodes, err := hq.Limit(1).All(setContextOp(ctx, hq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hosts.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hq *HostsQuery) FirstX(ctx context.Context) *Hosts {
	node, err := hq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Hosts ID from the query.
// Returns a *NotFoundError when no Hosts ID was found.
func (hq *HostsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hq.Limit(1).IDs(setContextOp(ctx, hq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hosts.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hq *HostsQuery) FirstIDX(ctx context.Context) int {
	id, err := hq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Hosts entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Hosts entity is found.
// Returns a *NotFoundError when no Hosts entities are found.
func (hq *HostsQuery) Only(ctx context.Context) (*Hosts, error) {
	nodes, err := hq.Limit(2).All(setContextOp(ctx, hq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hosts.Label}
	default:
		return nil, &NotSingularError{hosts.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hq *HostsQuery) OnlyX(ctx context.Context) *Hosts {
	node, err := hq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Hosts ID in the query.
// Returns a *NotSingularError when more than one Hosts ID is found.
// Returns a *NotFoundError when no entities are found.
func (hq *HostsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hq.Limit(2).IDs(setContextOp(ctx, hq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hosts.Label}
	default:
		err = &NotSingularError{hosts.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hq *HostsQuery) OnlyIDX(ctx context.Context) int {
	id, err := hq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HostsSlice.
func (hq *HostsQuery) All(ctx context.Context) ([]*Hosts, error) {
	ctx = setContextOp(ctx, hq.ctx, "All")
	if err := hq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Hosts, *HostsQuery]()
	return withInterceptors[[]*Hosts](ctx, hq, qr, hq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hq *HostsQuery) AllX(ctx context.Context) []*Hosts {
	nodes, err := hq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Hosts IDs.
func (hq *HostsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hq.ctx.Unique == nil && hq.path != nil {
		hq.Unique(true)
	}
	ctx = setContextOp(ctx, hq.ctx, "IDs")
	if err = hq.Select(hosts.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hq *HostsQuery) IDsX(ctx context.Context) []int {
	ids, err := hq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hq *HostsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hq.ctx, "Count")
	if err := hq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hq, querierCount[*HostsQuery](), hq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hq *HostsQuery) CountX(ctx context.Context) int {
	count, err := hq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hq *HostsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hq.ctx, "Exist")
	switch _, err := hq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hq *HostsQuery) ExistX(ctx context.Context) bool {
	exist, err := hq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HostsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hq *HostsQuery) Clone() *HostsQuery {
	if hq == nil {
		return nil
	}
	return &HostsQuery{
		config:     hq.config,
		ctx:        hq.ctx.Clone(),
		order:      append([]hosts.OrderOption{}, hq.order...),
		inters:     append([]Interceptor{}, hq.inters...),
		predicates: append([]predicate.Hosts{}, hq.predicates...),
		withFolder: hq.withFolder.Clone(),
		withKey:    hq.withKey.Clone(),
		// clone intermediate query.
		sql:  hq.sql.Clone(),
		path: hq.path,
	}
}

// WithFolder tells the query-builder to eager-load the nodes that are connected to
// the "folder" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HostsQuery) WithFolder(opts ...func(*FoldersQuery)) *HostsQuery {
	query := (&FoldersClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withFolder = query
	return hq
}

// WithKey tells the query-builder to eager-load the nodes that are connected to
// the "key" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HostsQuery) WithKey(opts ...func(*KeysQuery)) *HostsQuery {
	query := (&KeysClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withKey = query
	return hq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Hosts.Query().
//		GroupBy(hosts.FieldLabel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hq *HostsQuery) GroupBy(field string, fields ...string) *HostsGroupBy {
	hq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HostsGroupBy{build: hq}
	grbuild.flds = &hq.ctx.Fields
	grbuild.label = hosts.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//	}
//
//	client.Hosts.Query().
//		Select(hosts.FieldLabel).
//		Scan(ctx, &v)
func (hq *HostsQuery) Select(fields ...string) *HostsSelect {
	hq.ctx.Fields = append(hq.ctx.Fields, fields...)
	sbuild := &HostsSelect{HostsQuery: hq}
	sbuild.label = hosts.Label
	sbuild.flds, sbuild.scan = &hq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HostsSelect configured with the given aggregations.
func (hq *HostsQuery) Aggregate(fns ...AggregateFunc) *HostsSelect {
	return hq.Select().Aggregate(fns...)
}

func (hq *HostsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hq); err != nil {
				return err
			}
		}
	}
	for _, f := range hq.ctx.Fields {
		if !hosts.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hq.path != nil {
		prev, err := hq.path(ctx)
		if err != nil {
			return err
		}
		hq.sql = prev
	}
	return nil
}

func (hq *HostsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Hosts, error) {
	var (
		nodes       = []*Hosts{}
		withFKs     = hq.withFKs
		_spec       = hq.querySpec()
		loadedTypes = [2]bool{
			hq.withFolder != nil,
			hq.withKey != nil,
		}
	)
	if hq.withFolder != nil || hq.withKey != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, hosts.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Hosts).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Hosts{config: hq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hq.withFolder; query != nil {
		if err := hq.loadFolder(ctx, query, nodes, nil,
			func(n *Hosts, e *Folders) { n.Edges.Folder = e }); err != nil {
			return nil, err
		}
	}
	if query := hq.withKey; query != nil {
		if err := hq.loadKey(ctx, query, nodes, nil,
			func(n *Hosts, e *Keys) { n.Edges.Key = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hq *HostsQuery) loadFolder(ctx context.Context, query *FoldersQuery, nodes []*Hosts, init func(*Hosts), assign func(*Hosts, *Folders)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Hosts)
	for i := range nodes {
		if nodes[i].folders_host == nil {
			continue
		}
		fk := *nodes[i].folders_host
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(folders.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "folders_host" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (hq *HostsQuery) loadKey(ctx context.Context, query *KeysQuery, nodes []*Hosts, init func(*Hosts), assign func(*Hosts, *Keys)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Hosts)
	for i := range nodes {
		if nodes[i].keys_host == nil {
			continue
		}
		fk := *nodes[i].keys_host
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(keys.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "keys_host" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (hq *HostsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hq.querySpec()
	_spec.Node.Columns = hq.ctx.Fields
	if len(hq.ctx.Fields) > 0 {
		_spec.Unique = hq.ctx.Unique != nil && *hq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hq.driver, _spec)
}

func (hq *HostsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hosts.Table, hosts.Columns, sqlgraph.NewFieldSpec(hosts.FieldID, field.TypeInt))
	_spec.From = hq.sql
	if unique := hq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hq.path != nil {
		_spec.Unique = true
	}
	if fields := hq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hosts.FieldID)
		for i := range fields {
			if fields[i] != hosts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hq *HostsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hq.driver.Dialect())
	t1 := builder.Table(hosts.Table)
	columns := hq.ctx.Fields
	if len(columns) == 0 {
		columns = hosts.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hq.sql != nil {
		selector = hq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hq.ctx.Unique != nil && *hq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hq.predicates {
		p(selector)
	}
	for _, p := range hq.order {
		p(selector)
	}
	if offset := hq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HostsGroupBy is the group-by builder for Hosts entities.
type HostsGroupBy struct {
	selector
	build *HostsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hgb *HostsGroupBy) Aggregate(fns ...AggregateFunc) *HostsGroupBy {
	hgb.fns = append(hgb.fns, fns...)
	return hgb
}

// Scan applies the selector query and scans the result into the given value.
func (hgb *HostsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hgb.build.ctx, "GroupBy")
	if err := hgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HostsQuery, *HostsGroupBy](ctx, hgb.build, hgb, hgb.build.inters, v)
}

func (hgb *HostsGroupBy) sqlScan(ctx context.Context, root *HostsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hgb.fns))
	for _, fn := range hgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hgb.flds)+len(hgb.fns))
		for _, f := range *hgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HostsSelect is the builder for selecting fields of Hosts entities.
type HostsSelect struct {
	*HostsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hs *HostsSelect) Aggregate(fns ...AggregateFunc) *HostsSelect {
	hs.fns = append(hs.fns, fns...)
	return hs
}

// Scan applies the selector query and scans the result into the given value.
func (hs *HostsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hs.ctx, "Select")
	if err := hs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HostsQuery, *HostsSelect](ctx, hs.HostsQuery, hs, hs.inters, v)
}

func (hs *HostsSelect) sqlScan(ctx context.Context, root *HostsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hs.fns))
	for _, fn := range hs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
