// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function ClosePty(arg1) {
  return window['go']['main']['App']['ClosePty'](arg1);
}

export function CreateLocalPty(arg1) {
  return window['go']['main']['App']['CreateLocalPty'](arg1);
}

export function CreateSshPty(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSshPty'](arg1, arg2, arg3, arg4);
}

export function DelHost(arg1) {
  return window['go']['main']['App']['DelHost'](arg1);
}

export function GetHost(arg1) {
  return window['go']['main']['App']['GetHost'](arg1);
}

export function GetLocalPtyList() {
  return window['go']['main']['App']['GetLocalPtyList']();
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePty'](arg1, arg2, arg3);
}

export function UpdHost(arg1) {
  return window['go']['main']['App']['UpdHost'](arg1);
}

export function WriteToPty(arg1, arg2) {
  return window['go']['main']['App']['WriteToPty'](arg1, arg2);
}
