// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Folders is the predicate function for folders builders.
type Folders func(*sql.Selector)

// Hosts is the predicate function for hosts builders.
type Hosts func(*sql.Selector)

// Keys is the predicate function for keys builders.
type Keys func(*sql.Selector)
